name: gen-docs

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - '*'

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [^8.0]
    name: Docs P${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Composer
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Download
        run: wget --quiet --show-progress --no-clobber https://github.com/code-lts/doctum/releases/download/v5.5.4/doctum.phar

      - name: Generate
        run: |
          php doctum.phar update doctum.php

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
